/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Lead {
  'id' : bigint,
  'status' : LeadStatus,
  'owner' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'updatedAt' : bigint,
  'company' : string,
  'notes' : Array<Note>,
  'dealValue' : number,
  'phone' : string,
}
export interface LeadInput {
  'name' : string,
  'email' : string,
  'company' : string,
  'dealValue' : number,
  'phone' : string,
}
export type LeadStatus = { 'new' : null } |
  { 'closedWon' : null } |
  { 'proposal' : null } |
  { 'contacted' : null } |
  { 'qualified' : null } |
  { 'closedLost' : null };
export interface LeadUpdateInput {
  'id' : bigint,
  'email' : [] | [string],
  'company' : [] | [string],
  'dealValue' : [] | [number],
  'phone' : [] | [string],
}
export interface Note { 'text' : string, 'timestamp' : bigint }
export interface Stats {
  'closedWon' : bigint,
  'activeDeals' : bigint,
  'totalPipelineValue' : number,
  'recentActivity' : Array<Lead>,
  'totalLeads' : bigint,
  'conversionRate' : number,
  'closedLost' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addLeadNote' : ActorMethod<[bigint, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createLead' : ActorMethod<[LeadInput], bigint>,
  'deleteLead' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLead' : ActorMethod<[bigint], Lead>,
  'getLeadsByOwner' : ActorMethod<[Principal], Array<Lead>>,
  'getStats' : ActorMethod<[], Stats>,
  'getSuggestions' : ActorMethod<[bigint], Array<string>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listLeads' : ActorMethod<[], Array<Lead>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateLead' : ActorMethod<[LeadUpdateInput], undefined>,
  'updateLeadStatus' : ActorMethod<[bigint, LeadStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];