/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const LeadInput = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'dealValue' : IDL.Float64,
  'phone' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const LeadStatus = IDL.Variant({
  'new' : IDL.Null,
  'closedWon' : IDL.Null,
  'proposal' : IDL.Null,
  'contacted' : IDL.Null,
  'qualified' : IDL.Null,
  'closedLost' : IDL.Null,
});
export const Note = IDL.Record({ 'text' : IDL.Text, 'timestamp' : IDL.Int });
export const Lead = IDL.Record({
  'id' : IDL.Nat,
  'status' : LeadStatus,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'updatedAt' : IDL.Int,
  'company' : IDL.Text,
  'notes' : IDL.Vec(Note),
  'dealValue' : IDL.Float64,
  'phone' : IDL.Text,
});
export const Stats = IDL.Record({
  'closedWon' : IDL.Nat,
  'activeDeals' : IDL.Nat,
  'totalPipelineValue' : IDL.Float64,
  'recentActivity' : IDL.Vec(Lead),
  'totalLeads' : IDL.Nat,
  'conversionRate' : IDL.Float64,
  'closedLost' : IDL.Nat,
});
export const LeadUpdateInput = IDL.Record({
  'id' : IDL.Nat,
  'email' : IDL.Opt(IDL.Text),
  'company' : IDL.Opt(IDL.Text),
  'dealValue' : IDL.Opt(IDL.Float64),
  'phone' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addLeadNote' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createLead' : IDL.Func([LeadInput], [IDL.Nat], []),
  'deleteLead' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLead' : IDL.Func([IDL.Nat], [Lead], ['query']),
  'getLeadsByOwner' : IDL.Func([IDL.Principal], [IDL.Vec(Lead)], ['query']),
  'getStats' : IDL.Func([], [Stats], ['query']),
  'getSuggestions' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateLead' : IDL.Func([LeadUpdateInput], [], []),
  'updateLeadStatus' : IDL.Func([IDL.Nat, LeadStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const LeadInput = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'dealValue' : IDL.Float64,
    'phone' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const LeadStatus = IDL.Variant({
    'new' : IDL.Null,
    'closedWon' : IDL.Null,
    'proposal' : IDL.Null,
    'contacted' : IDL.Null,
    'qualified' : IDL.Null,
    'closedLost' : IDL.Null,
  });
  const Note = IDL.Record({ 'text' : IDL.Text, 'timestamp' : IDL.Int });
  const Lead = IDL.Record({
    'id' : IDL.Nat,
    'status' : LeadStatus,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'updatedAt' : IDL.Int,
    'company' : IDL.Text,
    'notes' : IDL.Vec(Note),
    'dealValue' : IDL.Float64,
    'phone' : IDL.Text,
  });
  const Stats = IDL.Record({
    'closedWon' : IDL.Nat,
    'activeDeals' : IDL.Nat,
    'totalPipelineValue' : IDL.Float64,
    'recentActivity' : IDL.Vec(Lead),
    'totalLeads' : IDL.Nat,
    'conversionRate' : IDL.Float64,
    'closedLost' : IDL.Nat,
  });
  const LeadUpdateInput = IDL.Record({
    'id' : IDL.Nat,
    'email' : IDL.Opt(IDL.Text),
    'company' : IDL.Opt(IDL.Text),
    'dealValue' : IDL.Opt(IDL.Float64),
    'phone' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addLeadNote' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createLead' : IDL.Func([LeadInput], [IDL.Nat], []),
    'deleteLead' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLead' : IDL.Func([IDL.Nat], [Lead], ['query']),
    'getLeadsByOwner' : IDL.Func([IDL.Principal], [IDL.Vec(Lead)], ['query']),
    'getStats' : IDL.Func([], [Stats], ['query']),
    'getSuggestions' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateLead' : IDL.Func([LeadUpdateInput], [], []),
    'updateLeadStatus' : IDL.Func([IDL.Nat, LeadStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };