/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Lead {
    id: bigint;
    status: LeadStatus;
    owner: Principal;
    name: string;
    createdAt: bigint;
    email: string;
    updatedAt: bigint;
    company: string;
    notes: Array<Note>;
    dealValue: number;
    phone: string;
}
export interface LeadUpdateInput {
    id: bigint;
    email?: string;
    company?: string;
    dealValue?: number;
    phone?: string;
}
export interface Stats {
    closedWon: bigint;
    activeDeals: bigint;
    totalPipelineValue: number;
    recentActivity: Array<Lead>;
    totalLeads: bigint;
    conversionRate: number;
    closedLost: bigint;
}
export interface LeadInput {
    name: string;
    email: string;
    company: string;
    dealValue: number;
    phone: string;
}
export interface UserProfile {
    name: string;
}
export interface Note {
    text: string;
    timestamp: bigint;
}
export enum LeadStatus {
    new_ = "new",
    closedWon = "closedWon",
    proposal = "proposal",
    contacted = "contacted",
    qualified = "qualified",
    closedLost = "closedLost"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addLeadNote(leadId: bigint, noteText: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createLead(leadInput: LeadInput): Promise<bigint>;
    deleteLead(leadId: bigint): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getLead(leadId: bigint): Promise<Lead>;
    getLeadsByOwner(owner: Principal): Promise<Array<Lead>>;
    getStats(): Promise<Stats>;
    getSuggestions(leadId: bigint): Promise<Array<string>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listLeads(): Promise<Array<Lead>>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateLead(input: LeadUpdateInput): Promise<void>;
    updateLeadStatus(leadId: bigint, newStatus: LeadStatus): Promise<void>;
}
import type { Lead as _Lead, LeadStatus as _LeadStatus, LeadUpdateInput as _LeadUpdateInput, Note as _Note, Stats as _Stats, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addLeadNote(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addLeadNote(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLeadNote(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createLead(arg0: LeadInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createLead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLead(arg0);
            return result;
        }
    }
    async deleteLead(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLead(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLead(arg0: bigint): Promise<Lead> {
        if (this.processError) {
            try {
                const result = await this.actor.getLead(arg0);
                return from_candid_Lead_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLead(arg0);
            return from_candid_Lead_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeadsByOwner(arg0: Principal): Promise<Array<Lead>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeadsByOwner(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeadsByOwner(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStats(): Promise<Stats> {
        if (this.processError) {
            try {
                const result = await this.actor.getStats();
                return from_candid_Stats_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStats();
            return from_candid_Stats_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSuggestions(arg0: bigint): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSuggestions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSuggestions(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listLeads(): Promise<Array<Lead>> {
        if (this.processError) {
            try {
                const result = await this.actor.listLeads();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listLeads();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateLead(arg0: LeadUpdateInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLead(to_candid_LeadUpdateInput_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLead(to_candid_LeadUpdateInput_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateLeadStatus(arg0: bigint, arg1: LeadStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLeadStatus(arg0, to_candid_LeadStatus_n15(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLeadStatus(arg0, to_candid_LeadStatus_n15(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_LeadStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeadStatus): LeadStatus {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Lead_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Lead): Lead {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Stats_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Stats): Stats {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closedWon: bigint;
    activeDeals: bigint;
    totalPipelineValue: number;
    recentActivity: Array<_Lead>;
    totalLeads: bigint;
    conversionRate: number;
    closedLost: bigint;
}): {
    closedWon: bigint;
    activeDeals: bigint;
    totalPipelineValue: number;
    recentActivity: Array<Lead>;
    totalLeads: bigint;
    conversionRate: number;
    closedLost: bigint;
} {
    return {
        closedWon: value.closedWon,
        activeDeals: value.activeDeals,
        totalPipelineValue: value.totalPipelineValue,
        recentActivity: from_candid_vec_n10(_uploadFile, _downloadFile, value.recentActivity),
        totalLeads: value.totalLeads,
        conversionRate: value.conversionRate,
        closedLost: value.closedLost
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _LeadStatus;
    owner: Principal;
    name: string;
    createdAt: bigint;
    email: string;
    updatedAt: bigint;
    company: string;
    notes: Array<_Note>;
    dealValue: number;
    phone: string;
}): {
    id: bigint;
    status: LeadStatus;
    owner: Principal;
    name: string;
    createdAt: bigint;
    email: string;
    updatedAt: bigint;
    company: string;
    notes: Array<Note>;
    dealValue: number;
    phone: string;
} {
    return {
        id: value.id,
        status: from_candid_LeadStatus_n8(_uploadFile, _downloadFile, value.status),
        owner: value.owner,
        name: value.name,
        createdAt: value.createdAt,
        email: value.email,
        updatedAt: value.updatedAt,
        company: value.company,
        notes: value.notes,
        dealValue: value.dealValue,
        phone: value.phone
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    new: null;
} | {
    closedWon: null;
} | {
    proposal: null;
} | {
    contacted: null;
} | {
    qualified: null;
} | {
    closedLost: null;
}): LeadStatus {
    return "new" in value ? LeadStatus.new : "closedWon" in value ? LeadStatus.closedWon : "proposal" in value ? LeadStatus.proposal : "contacted" in value ? LeadStatus.contacted : "qualified" in value ? LeadStatus.qualified : "closedLost" in value ? LeadStatus.closedLost : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Lead>): Array<Lead> {
    return value.map((x)=>from_candid_Lead_n6(_uploadFile, _downloadFile, x));
}
function to_candid_LeadStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeadStatus): _LeadStatus {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_LeadUpdateInput_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeadUpdateInput): _LeadUpdateInput {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    email?: string;
    company?: string;
    dealValue?: number;
    phone?: string;
}): {
    id: bigint;
    email: [] | [string];
    company: [] | [string];
    dealValue: [] | [number];
    phone: [] | [string];
} {
    return {
        id: value.id,
        email: value.email ? candid_some(value.email) : candid_none(),
        company: value.company ? candid_some(value.company) : candid_none(),
        dealValue: value.dealValue ? candid_some(value.dealValue) : candid_none(),
        phone: value.phone ? candid_some(value.phone) : candid_none()
    };
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeadStatus): {
    new: null;
} | {
    closedWon: null;
} | {
    proposal: null;
} | {
    contacted: null;
} | {
    qualified: null;
} | {
    closedLost: null;
} {
    return value == LeadStatus.new ? {
        new_: null
    } : value == LeadStatus.closedWon ? {
        closedWon: null
    } : value == LeadStatus.proposal ? {
        proposal: null
    } : value == LeadStatus.contacted ? {
        contacted: null
    } : value == LeadStatus.qualified ? {
        qualified: null
    } : value == LeadStatus.closedLost ? {
        closedLost: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
